version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:8000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: alunos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
